"""empty message

Revision ID: 6a5c41bd2e8b
Revises: 7aec736efa96
Create Date: 2021-10-28 22:05:50.925038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5c41bd2e8b'
down_revision = '7aec736efa96'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('carts', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('carts', 'is_submitted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'is_submitted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('carts', 'updated_on')
    op.drop_column('carts', 'created_on')
    # ### end Alembic commands ###
