"""empty message

Revision ID: 7aec736efa96
Revises: f157c7b19e92
Create Date: 2021-10-28 21:30:41.379270

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7aec736efa96'
down_revision = 'f157c7b19e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('is_submitted', sa.Boolean(), nullable=True))
    op.drop_column('checkout', 'is_submitted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout', sa.Column('is_submitted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('carts', 'is_submitted')
    # ### end Alembic commands ###
