"""empty message

Revision ID: f157c7b19e92
Revises: f9ecb396890b
Create Date: 2021-10-28 21:27:23.341598

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f157c7b19e92'
down_revision = 'f9ecb396890b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout', sa.Column('is_submitted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkout', 'is_submitted')
    # ### end Alembic commands ###
