"""changed the relation

Revision ID: f9ecb396890b
Revises: d593fd345722
Create Date: 2021-10-13 20:56:10.924833

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f9ecb396890b'
down_revision = 'd593fd345722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.drop_constraint('checkout_user_id_fkey', 'checkout', type_='foreignkey')
    op.create_foreign_key(None, 'checkout', 'carts', ['cart_id'], ['id'])
    op.drop_column('checkout', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'checkout', type_='foreignkey')
    op.create_foreign_key('checkout_user_id_fkey', 'checkout', 'users', ['user_id'], ['id'])
    op.drop_column('checkout', 'cart_id')
    # ### end Alembic commands ###
